version: "3"

services:
  origin:
    hostname: origin
    build: ./basics
    image: debian
    container_name: origin
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes:/volumes

  fw:
    hostname: fw
    image: debian
    container_name: fw
    tty: true
    cap_add:
      - ALL
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.5
    privileged: true

  destiny:
    hostname: destiny
    image: debian
    container_name: destiny
    tty: true
    cap_add:
      - ALL
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.6

networks:
  net-10.9.0.0:
    name: net-10.9.0.0
    ipam:
      config:
        - subnet: 10.9.0.0/24
