services:
  origin:
    hostname: origin
    build: ./basics/origin
    container_name: origin
    tty: true
    cap_add:
      - ALL
    networks:
      net-10.8.0.0:
        ipv4_address: 10.8.0.4
    privileged: true

  fw:
    hostname: fw
    build: ./basics/fw
    container_name: fw
    tty: true
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/root/fwmanager/run-tests:/root/run-tests:rw"
      - "/root/.bashrc:/root/.bashrc:rw"
    cap_add:
      - ALL
    networks:
      net-10.8.0.0:
        ipv4_address: 10.8.0.5
      net-10.9.0.0:
        ipv4_address: 10.9.0.5
    privileged: true

  destiny:
    hostname: destiny
    build: ./basics/destiny
    container_name: destiny
    tty: true
    cap_add:
      - ALL
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.6

networks:  
  net-10.8.0.0:
    name: net-10.8.0.0
    ipam:
      config:
        - subnet: 10.8.0.0/24
    driver_opts:
      com.docker.network.bridge.name: origin

  net-10.9.0.0:
    name: net-10.9.0.0
    ipam:
      config:
        - subnet: 10.9.0.0/24
    driver_opts:
      com.docker.network.bridge.name: destiny
